---
# DHCP Server to be installed on IP: 139.229.162.250/24
dhcp_pools:
  "test.vm.dev..lsst.org":
    network: "10.0.0.0"
    mask: "255.255.255.0"
    range:
      - '10.0.0.100 10.0.0.200'
    gateway: "10.0.0.1"
    failover: "failover-partner"
ignored_subnets:
  eth0:
    network: "139.229.160.0"
    mask: "255.255.255.0"
dnsdomain:
  - "cp.cl.lsst.org"
dnssearchdomains:
  - "cp.cl.lsst.org"
  - "cl.lsst.org"
  - "lsst.org"
  - "lsst.local"
  - "162.229.136.in-addr.arpa"
nameservers:
  - "139.229.136.35"  # pi-hole temporary DNS content filtering
  #- "140.252.32.45"  # it doesn't make sense to have
ntpservers:
  - "ntp.shoa.cl"
dhcp_interfaces:
  - "eth0"
